# -*- coding: utf-8 -*-
"""Política (r,Q,T)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9A0wHma_cJVjlt33z_hTJ1jgJmpR40h
"""

import pandas as pd

def politica_inventario(demanda, r, Q, T, costo_orden, max_ordenes_anuales, stock_inicial, leadtime):
    inventario = {-1: stock_inicial}  # Diccionario inventario inicial
    compras = {}  # Diccionario compras en cada periodo
    ventas = 0
    ordenes_anuales = 0
    quiebres_stock = 0
    demanda_perdida = {}  # Diccionario demanda perdida en cada día

    dia = 1
    while dia <= max(demanda.keys()):
        demanda_dia = demanda.get(dia, 0)  # Obtener la demanda del día (0 si no hay demanda)

        inventario[dia] = inventario.get(dia - 1, 0) + compras.get(dia - leadtime, 0)
        if inventario[dia] < demanda_dia:
            quiebres_stock += 1
            demanda_perdida[dia] = demanda_dia - inventario[dia]
            # ¿qué hacer si hay demanda perdida? --> aplicar otra política??
        else:
            ventas += demanda_dia
            inventario[dia] -= demanda_dia

        if dia % 7 == 0:  # Aplicar la política periódica (cada 7 dias)
            if inventario[dia] < r:
                ordenes_anuales += 1
                compras[dia] = Q
                inventario[dia] += Q

        dia += 1

    ganancias_netas = ventas - (ordenes_anuales * costo_orden)

    return ganancias_netas, quiebres_stock, demanda_perdida